use_frameworks!

platform :ios, '8.0'

target 'CJPBaseComponents_Example' do
  pod 'CJPBaseComponents', :path => '../'

  target 'CJPBaseComponents_Tests' do
    inherit! :search_paths

    
  end
end
